# Generated by Django 5.2.9 on 2026-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, unique=True, verbose_name="адрес"),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="широта"),
                ),
                (
                    "lon",
                    models.FloatField(blank=True, null=True, verbose_name="долгота"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="запрос создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "локация",
                "verbose_name_plural": "локации",
            },
        ),
    ]
