# Generated by Django 5.2.9 on 2026-01-09 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_alter_orderitem_options_order_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="цена на момент заказа",
            ),
            preserve_default=False,
        ),
    ]
