# Generated by Django 5.2.9 on 2026-01-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0041_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Комментарий клиента к заказу",
                verbose_name="комментарий",
            ),
        ),
    ]
