# Generated by Django 5.2.9 on 2026-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_order_called_at_order_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[
                    ("unknown", "не определено"),
                    ("cash", "Наличными"),
                    ("card", "Картой"),
                ],
                db_index=True,
                default="unknown",
                max_length=50,
                verbose_name="оплата",
            ),
        ),
    ]
