# Generated by Django 5.2.9 on 2026-01-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0044_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличными"), ("card", "Картой")],
                db_index=True,
                max_length=50,
                verbose_name="оплата",
            ),
        ),
    ]
