# Generated by Django 5.2.9 on 2026-01-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0045_alter_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unprocessed", "Необработанный"),
                    ("restaurant_confirmed", "Готовится"),
                    ("delivery_started", "Передан курьеру"),
                    ("completed", "Заказ выполнен"),
                ],
                db_index=True,
                default="unprocessed",
                max_length=50,
                verbose_name="статус",
            ),
        ),
    ]
