# Generated by Django 5.2.9 on 2026-01-27 16:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0046_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=200, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="фамилия"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="телефон"
            ),
        ),
    ]
