# Generated by Django 5.2.9 on 2026-02-05 18:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0047_alter_order_address_alter_order_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="звонок"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="создан"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="доставлен"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, verbose_name="телефон"
            ),
        ),
    ]
